#!/usr/bin/expect -f

spawn setup-ds-admin.pl
expect "continue with set up"
send "yes\r"
expect "Would you like to continue"
send "yes\r"
expect "Choose a setup type"
send "2\r"
expect "Computer name"
send "{{ldap_server_fqdn}}\r"
expect "System User"
send "ldapadmin\r"
expect "System Group"
send "ldapadmin\r"
expect "configuration directory server"
send "no\r"
expect "administrator ID"
send "admin\r"
expect "Password"
send "{{admin_password}}\r"
expect "Password (confirm)"
send "{{admin_password}}\r"
expect "Administration Domain"
send "{{administration_domain}}\r"
expect "Directory server network port"
send "389\r"
expect "Directory server identifier"
send "\r"
expect "Suffix"
send "\r"
expect "Directory Manager DN"
send "\r"
expect "Password"
send "{{admin_password}}\r"
expect "Password (confirm)"
send "{{admin_password}}\r"
expect "Administration port"
send "9830\r"
expect "Are you ready to set up your servers"
send "yes\r"


expect "Not there for sure"
send_user "$expect_out(buffer)"

exit 0
